### ISSUE TITLE
App dies after pressing start button on Pixel XL emulator

### ISSUE THREAD

**Issue by clone278** [clone278/BirdQuiz#2]
<img width="372" alt="screen shot 2017-08-16 at 12 33 17 pm" src="https://user-images.githubusercontent.com/2619133/29342504-3e7110a0-827f-11e7-8142-3cce5f00ec07.png">

Caused by: java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Integer.java:483)
at java.lang.Integer.parseInt(Integer.java:556)
at com.gotg.birdquiz.MainActivityFragment.updateNumberOfQuestions(MainActivityFragment.java:117)

**Comment by clone278** [comment]
Noticed that the default value for android:key="pref_numberOfQuestions" did not exist as a value as per the array for num_questions_list

**Comment by clone278** [comment]
Change a couple of things and now working.  Was instantiating the numQuestions integer and wasn't you the getInt call from the SharePreferences utility.  Committed under #93d80d0c61fdde0436ce217956f6ef241636108e
