### ISSUE TITLE
App fails at quiz end on Pixel XL emulator

### ISSUE THREAD

**Issue by clone278** [clone278/BirdQuiz#4]
08-16 14:24:12.798 6104-6104/com.gotg.birdquiz E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.gotg.birdquiz, PID: 6104
                                                                 java.lang.IllegalStateException: Fragment null must be a public static class to be properly recreated from instance state.
at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:384)
at android.support.v4.app.BackStackRecord.add(BackStackRecord.java:363)
at android.support.v4.app.DialogFragment.show(DialogFragment.java:142)
at com.gotg.birdquiz.MainActivityFragment$2.onClick(MainActivityFragment.java:372)

**Comment by clone278** [comment]
Converted from using an anonymous DialogFragment class, for the displaying the results, to a static inner class called ResultsDialogFragment.
